### PR TITLE
Pt15 code coverage

### PR DESCRIPTION
**Pull request by HasuNoHana**

### CODE REVIEW

**Review by p-karbownik — CHANGES_REQUESTED** [review]
watchAll flag is unnecessary here because there is already the environment variable 'CI', which do the same job

**Comment by HasuNoHana** [comment]
> watchAll flag is unnecessary here because there is already the environment variable 'CI', which do the same job
I just tried, I have run it in pipe line and without that fage it doesen't work, I will paste the status of request from jenkins.
jenkins_request
image

**Comment by HasuNoHana** [comment]
After I swiched back to having a flage everything works pearfectly.
image
image

**Comment by p-karbownik** [comment]
Kk, I found that the evn variable was missing and I've added it, so now it's working perfectly. Check it in jenkins

**Comment by HasuNoHana** [comment]
You are right, it might be a better solution since it is supported more than wachAll flag. I checked and it is working, you can merge if you agree

**Review by p-karbownik — APPROVED** [review]
Looks good, I'll merge it

**Pull request merged**
